spring:
  application:
    name: aula-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
aula-microservice:
  greeting: "Hola muchacho, "
  default-value: "és cabrón?"