spring:
  application:
    name: aula-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
aula-microservice:
  greeting: "Ciao bambino!"
  default-value: "Vá bene?"